export const ACTION = Object.freeze({
    SELECT_FILE: "SELECT_FILE",
    BEGIN_BROWSE_NEW_FILES: "BEGIN_BROWSE_NEW_FILES",
    END_BROWSE_NEW_FILES_SUCCESS: "END_BROWSE_NEW_FILES_SUCCESS",
    END_BROWSE_NEW_FILES_FAIL: "END_BROWSE_NEW_FILES_FAIL",
    BROWSE_FAIL: "BROWSE_FAIL",
    BEGIN_DOWNLOAD_FILE: "BEGIN_DOWNLOAD_FILE",
    END_DOWNLOAD_FILE_SUCCESS: "END_DOWNLOAD_FILE_SUCCESS",
    END_DOWNLOAD_FILE_FAIL: "END_DOWNLOAD_FILE_FAIL",

    PASS_CHANGED: "PASS_CHANGED",
    USER_CHANGED: "USER_CHANGED",
    BEGIN_LOGIN: "BEGIN_LOGIN",
    AUTHENTICATED_WITH_SERVER: "AUTHENTICATED_WITH_SERVER",
    AUTH_REJECTED_FROM_SERVER: "AUTH_REJECTED_FROM_SERVER",
    BEGIN_CHECK_AUTHENTICATION_WITH_SERVER: "BEGIN_CHECK_AUTHENTICATION_WITH_SERVER"

});

export const FILE_TYPES = Object.freeze({
    FILE: "file",
    FOLDER: "folder"
});

export const NETWORK_FAIL_REASONS = Object.freeze({
    AUTHENTICATION_MISSING: "AUTHENTICATION_MISSING",
    OTHER: "OTHER"
});