export const ACTION = Object.freeze({
    BEGIN_BROWSE_NEW_FILES: "BEGIN_BROWSE_NEW_FILES",
    END_BROWSE_NEW_FILES_SUCCESS: "END_BROWSE_NEW_FILES_SUCCESS",
    END_BROWSE_NEW_FILES_FAIL: "END_BROWSE_NEW_FILES_FAIL",
    BROWSE_FAIL: "BROWSE_FAIL",
    BEGIN_DOWNLOAD_FILE: "BEGIN_DOWNLOAD_FILE",
    END_DOWNLOAD_FILE_SUCCESS: "END_DOWNLOAD_FILE_SUCCESS",
    END_DOWNLOAD_FILE_FAIL: "END_DOWNLOAD_FILE_FAIL",
    BEGIN_PREVIEW_FILE: "BEGIN_PREVIEW_FILE",
    END_PREVIEW_FILE_SUCCESS: "END_PREVIEW_FILE_SUCCESS",
    FILE_NOT_PREVIEWABLE: "FILE_NOT_PREVIEWABLE",
    STOP_PREVIEW: "STOP_PREVIEW",

    LOGIN_PASS_CHANGED: "PASS_CHANGED",
    LOGIN_USER_CHANGED: "USER_CHANGED",

    SIGNUP_PASS_CHANGED: "SIGNUP_PASS_CHANGED",
    SIGNUP_CONFIRM_PASS_CHANGED: "SIGNUP_CONFIRM_PASS_CHANGED",
    SIGNUP_USER_CHANGED: "SIGNUP_USER_CHANGED",

    BEGIN_LOGIN: "BEGIN_LOGIN",
    AUTHENTICATED_WITH_SERVER: "AUTHENTICATED_WITH_SERVER",
    AUTH_REJECTED_FROM_SERVER: "AUTH_REJECTED_FROM_SERVER",
    BEGIN_CHECK_AUTHENTICATION_WITH_SERVER: "BEGIN_CHECK_AUTHENTICATION_WITH_SERVER",

    BEGIN_SIGNUP: "BEGIN_SIGNUP",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    END_UPLOAD_FILES_FAIL: "END_UPLOAD_FILES_FAIL",
    END_UPLOAD_FILES: "END_UPLOAD_FILES",
    BEGIN_UPLOAD_FILES: "BEGIN_UPLOAD_FILES",


    BEGIN_LOGOUT: "BEGIN_LOGOUT",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILED: "LOGOUT_FAILED",

    NAVIGATE_TO: "NAVIGATE_TO",
    SET_IS_SYNCHRONOUS_LOADING: "SET_IS_SYNCHRONOUS_LOADING",

    LOAD_ICON: "LOAD_ICON",

    TOGGLE_VIEW_MODE: "TOGGLE_VIEW_MODE"
});

export const FILE_TYPES = Object.freeze({
    FILE: "FILE",
    FOLDER: "FOLDER",
    IMAGE: "IMAGE",
    VIDEO: "VIDEO",
    AUDIO: "AUDIO"

});

export const NETWORK_FAIL_REASONS = Object.freeze({
    AUTHENTICATION_MISSING: "AUTHENTICATION_MISSING",
    OTHER: "OTHER"
});

//TODO add the supported extensions.
export const TYPE_EXTENSIONS = Object.freeze({
    IMAGE: ["jpg", "png", "jpeg", "cr2"],
    VIDEO_STREAMABLE: ["mp4", "avi", "wmv", "mkv", "webm"],
    AUDIO_STREAMABLE: ["mp3"]
});


export const PAGES = Object.freeze({
    FILE_BROWSER: "FILEBROWSER",
    PREVIEWER: "PREVIEWER",
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP"
});

export const INPUT_TYPES = Object.freeze({
    USER: "USER",
    PASSWORD: "PASSWORD",
    CONFIRM_PASSWORD: "CONFIRM_PASSWORD"
});

export const VIEW_MODE = Object.freeze({
    LIST: "LIST",
    THUMB: "THUMB"
});